<?php
/*
 * This file is part of Totara LMS
 *
 * Copyright (C) 2015 onwards Totara Learning Solutions LTD
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Brian Barnes <brian.barnes@totaralearning.com>
 * @author Joby Harding <joby.harding@totaralearning.com>
 * @package theme_oaklandcustomresponsive
 */

defined('MOODLE_INTERNAL') || die;

use theme_oaklandcustomresponsive\css_processor;

$component = 'theme_oaklandcustomresponsive';

if ($ADMIN->fulltree) {

    // Logo file setting.
    $name = "{$component}/logo";
    $title = new lang_string('logo', 'totara_core');
    $description = new lang_string('logodesc', 'totara_core');
    $setting = new admin_setting_configstoredfile($name, $title, $description, 'logo',0 ,['accepted_types' => 'web_image']);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Logo alt text.
    $name = "{$component}/alttext";
    $title = new lang_string('alttext', 'totara_core');
    $description = new lang_string('alttextdesc', 'totara_core');
    $setting = new admin_setting_configtext($name, $title, $description, '');
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Favicon file setting.
    $name = "{$component}/favicon";
    $title = new lang_string('favicon', 'totara_core');
    $description = new lang_string('favicondesc', 'totara_core');
    $setting = new admin_setting_configstoredfile($name, $title, $description, 'favicon', 0, array('accepted_types' => '.ico'));
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Enable / disable style overrides.
    // As settings-based style overrides are not Less processed
    // and colour variants are automatically generated by PHP
    // there is a small reduction in quality.
    $name = "{$component}/enablestyleoverrides";
    $title = new lang_string('enablestyleoverrides', $component);
    $description = new lang_string('enablestyleoverrides_desc', $component);
    $default = '1';
    $setting = new admin_setting_configcheckbox($name, $title, $description, $default);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Header background file setting.
    $name = "{$component}/headerbgimg";
    $title = new lang_string('headerbgimg', $component);
    $description = new lang_string('headerbgimgdesc', $component);
    $setting = new admin_setting_configstoredfile($name, $title, $description, 'headerbgimg',0 ,['accepted_types' => 'web_image']);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    $name = "{$component}/headerbgimgopacity";
    $title = new lang_string('headerbgimgopacity', $component);
    $description = new lang_string('headerbgimgopacitydesc', $component);
    $setting = new admin_setting_configtext($name, $title, $description, '');
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Body background file setting.
    $name = "{$component}/bodybgimg";
    $title = new lang_string('bodybgimg', $component);
    $description = new lang_string('bodybgimgdesc', $component);
    $setting = new admin_setting_configstoredfile($name, $title, $description, 'bodybgimg',0 ,['accepted_types' => 'web_image']);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Body background image opacity setting.
    $name = "{$component}/bodybgimgopacity";
    $title = new lang_string('bodybgimgopacity', $component);
    $description = new lang_string('bodybgimgopacitydesc', $component);
    $setting = new admin_setting_configtext($name, $title, $description, '');
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Site text color
    $name = "{$component}/textcolor";
    $title = get_string('textcolor', $component);
    $description = get_string('textcolor_desc', $component);
    $default = css_processor::$DEFAULT_TEXTCOLOR;
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Link colour setting.
    $name = "{$component}/linkcolor";
    $title = new lang_string('linkcolor', $component);
    $description = new lang_string('linkcolordesc', $component);
    $default = css_processor::$DEFAULT_LINKCOLOR;
    $previewconfig = array('selector' => 'a', 'style' => 'color');
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, $previewconfig);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Link visited colour setting.
    $name = "{$component}/linkvisitedcolor";
    $title = new lang_string('linkvisitedcolor', $component);
    $description = new lang_string('linkvisitedcolordesc', $component);
    $default = css_processor::$DEFAULT_LINKVISITEDCOLOR;
    $previewconfig = array('selector' => 'a:visited', 'style' => 'color');
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, $previewconfig);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Button colour setting.
    $name = "{$component}/buttoncolor";
    $title = new lang_string('buttoncolor',$component);
    $description = new lang_string('buttoncolordesc', $component);
    $default = css_processor::$DEFAULT_BUTTONCOLOR;
    $previewconfig = array('selector'=>'input[\'type=submit\']]', 'style'=>'background-color');
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, $previewconfig);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Site content background color.
    $name = "{$component}/bodybackground";
    $title = get_string('bodybackground', $component);
    $description = get_string('bodybackground_desc', $component);
    $default = css_processor::$DEFAULT_BODYBACKGROUND;
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Main content background color.
    $name = "{$component}/contentbackground";
    $title = get_string('contentbackground', $component);
    $description = get_string('contentbackground_desc', $component);
    $default = css_processor::$DEFAULT_CONTENTBACKGROUND;
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Page header background colour setting.
    $name = "{$component}/headerbgc";
    $title = new lang_string('headerbgc', $component);
    $description = new lang_string('headerbgcdesc', $component);
    $default = css_processor::$DEFAULT_HEADERBGC;
    $previewconfig = array('selector' => '#page-header', 'style' => 'backgroundColor');
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, $previewconfig);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Page header background colour 2 setting for Gradient.
    $name = "{$component}/headergradient";
    $title = get_string('headergradient', $component);
    $description = get_string('headerdescgradient', $component);
    $default = '';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Navigation text color.
    $name = "{$component}/navtextcolor";
    $title = get_string('navtextcolor', $component);
    $description = get_string('navtextcolor_desc', $component);
    $default = css_processor::$DEFAULT_NAVTEXTCOLOR;
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Footnote setting.
    $name = "{$component}/footnote";
    $title = get_string('footnote', $component);
    $description = get_string('footnotedesc', $component);
    $default = '';
    $setting = new admin_setting_confightmleditor($name, $title, $description, $default);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Custom CSS file.
    $name = "{$component}/customcss";
    $title = new lang_string('customcss',$component);
    $description = new lang_string('customcssdesc', $component);
    $setting = new admin_setting_configtextarea($name, $title, $description, '');
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Block header background colour setting.
    $name = "{$component}/blockheadercolor";
    $title = get_string('blockheadercolor', $component);
    $description = get_string('blockheadercolordesc', $component);
    $default = '#fc9920';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Block header background top gradient colour setting.
    $name = "{$component}/blockheadergradientstart";
    $title = get_string('blockheadergradientstart', $component);
    $description = get_string('blockheadergradientstartdesc', $component);
    $default = '#ffffff';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Block header text colour setting.
    $name = "{$component}/blockheadertextcolor";
    $title = get_string('blockheadertextcolor', $component);
    $description = get_string('blockheadertextcolordesc', $component);
    $default = '#4e4546';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Block body background colour setting.
    $name = "{$component}/blockcontentcolor";
    $title = get_string('blockcontentcolor', $component);
    $description = get_string('blockcontentcolordesc', $component);
    $default = '#ffffff';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    //--------------------NEW----------------------

    // Button text color setting.
    $name = "{$component}/buttontextcolor";
    $title = get_string('buttontextcolor', $component);
    $description = get_string('buttontextcolordesc', $component);
    $default = '#ffffff';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Menu Color
    $name = "{$component}/menucolor";
    $title = get_string('menucolor', $component);
    $description = get_string('menucolordesc', $component);
    $default = '#ffffff';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Menu Text Color
    $name = "{$component}/menutextcolor";
    $title = get_string('menutextcolor', $component);
    $description = get_string('menutextcolordesc', $component);
    $default = '#000000';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Selected Menu Color
    $name = "{$component}/selectedmenucolor";
    $title = get_string('selectedmenucolor', $component);
    $description = get_string('selectedmenucolordesc', $component);
    $default = '#ffffff';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Selected Menu Text Color
    $name = "{$component}/selectedmenutextcolor";
    $title = get_string('selectedmenutextcolor', $component);
    $description = get_string('selectedmenutextcolordesc', $component);
    $default = '#000000';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Sub Menu Item Color
    $name = "{$component}/submenucolor";
    $title = get_string('submenucolor', $component);
    $description = get_string('submenucolordesc', $component);
    $default = '#000000';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Sub Menu Text Color
    $name = "{$component}/submenutextcolor";
    $title = get_string('submenutextcolor', $component);
    $description = get_string('submenutextcolordesc', $component);
    $default = '#ffffff';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Selected Sub-Menu Color
    $name = "{$component}/selectedsubmenucolor";
    $title = get_string('selectedsubmenucolor', $component);
    $description = get_string('selectedsubmenucolordesc', $component);
    $default = '#000000';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Selected Sub-Menu Text Color
    $name = "{$component}/selectedsubmenutextcolor";
    $title = get_string('selectedsubmenutextcolor', $component);
    $description = get_string('selectedsubmenutextcolordesc', $component);
    $default = '#ffffff';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);


    // Hover Menu Item Color
    $name = "{$component}/hovermenucolor";
    $title = get_string('hovermenucolor', $component);
    $description = get_string('hovermenucolordesc', $component);
    $default = '#808080';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Hover Sub Menu Item Color
    $name = "{$component}/hoversubmenucolor";
    $title = get_string('hoversubmenucolor', $component);
    $description = get_string('hoversubmenucolordesc', $component);
    $default = '#808080';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    // Logged in Username Color
    $name = "{$component}/logged_in_usernamecolor";
    $title = get_string('logged_in_usernamecolor', $component);
    $description = get_string('logged_in_usernamecolordesc', $component);
    $default = '#ffffff';
    $setting = new admin_setting_configcolourpicker($name, $title, $description, $default, null, false);
    $setting->set_updatedcallback('theme_reset_all_caches');
    $settings->add($setting);

    //-------------END OAKLAND CUSTOM-------------------
}
